### ISSUE TITLE
i had lost privite key

### ISSUE THREAD

**Issue by fjykp123** [pointbiz/bitaddress.org#196]
i had generated 100 bitcoin addresses with Bulk Wallet on bitaddress.org. now i forgot privite key.but i have 100 bitcoin addresss.Can i get privite key back?

**Comment by secretrys13** [comment]
lost a private key, then lost all the coins. Private keys can not be restored

**Comment by thebtibadii** [comment]
Hi

**Comment by jonathancross** [comment]
@fjykp123 Addresses are public, there is nothing you can do with only addresses.  The entire Bitcoin system would be broken if there was a way to get the private key from the address. Sorry.

Please close this.

**Comment by fjykp123** [comment]
Is there a relationship between 100 addresses?  Maybe there are all use one seed?

**Comment by fjykp123** [comment]
> @fjykp123 Addresses are public, there is nothing you can do with only addresses. The entire Bitcoin system would be broken if there was a way to get the private key from the address. Sorry.
> 
> Please close this.

Is there a relationship between 100 addresses? Maybe there are all use one seed?

**Comment by jonathancross** [comment]
@fjykp123 No, every address would be seperate unless you already know the original seed used to generate them.  This is intentional.

**Comment by piyawat1984** [comment]
ฉันจะสร้างคีร์ส่วนตัวได้อย่างไร

**Comment by tnkmt** [comment]
> now i forgot privite key

In the ideal situation the private key is not something **you** may forget, because it's not intended to be remembered. 

Maybe you lost it? Or forget the password you are using for encrypting the keys?

Are you sure you lost the private keys? They are in the same line (on the second row) where is the public key (when using the "Bulk Wallet" feature).

It's looking like this (don't use those private keys and addresses!):

```
1,"18stFDD7zmfDxg3ncJQKs47itvpCrvuFxS","KzeVExMxC6sSLSDAbn6TAnVB99qvUUQRWNuosx2iD6WFuTSDx1SG"
2,"1NFYNwsMFTe83si1URA7LxLe6jasx2wfFW","L53tWoMU3BexxQwpYxSGxwN3mV5sGFLvrxetk1bNXvVV8KWHJDq3"
3,"16kfKTka1yMmRGqhakqcYTJxexExWqgsAV","L1gAxJmt3zLGjAYTNGvd4QgVMyrxGUwnsFzNJvpxDbx7NivrHwEh"
4,"1ASReymAVcg1j2x3PRXHAExfGGbaPHF7sY","KzAZxqSVgCVrA1AYsPzHd6XubMexbRJL2WKAW3x1Gys6R9XGav88"
```
In this example `18stFDD7zmfDxg3ncJQKs47itvpCrvuFxS` is the public key and `KzeVExMxC6sSLSDAbn6TAnVB99qvUUQRWNuosx2iD6WFuTSDx1SG` is the corresponding private key.

(I made them invalid by changing them just in case.)

**Comment by soniaklick** [comment]
Well, i was in the same situation until i sorted professional help. These guys helped me recover my wallet private key [secrettruthhackers.imfast.io], what would i have done when my wallet had investors bitcoin in there? Thanks to the secrettruthhackers.
