### ISSUE TITLE
feature request: add BIP38 to Wallet Details tab to support existing BIP32 addresses

### ISSUE THREAD

**Issue by moocowmoo** [pointbiz/bitaddress.org#44]
Please consider adding BIP38 encryption to the Wallet Details page.

I generate BIP32 chains for storage and would like to keep an encrypted key or two on me to sweep as needed.

Thanks!

**Comment by dooglus** [comment]
https://bitcoinpaperwallet.com/ has this feature already.

I played around with it and found that it creates different encrypted private keys than bitaddress does. But that appears to be because bitaddress is using [EC multiply mode](https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki#encryption-when-ec-multiply-mode-is-used) and bitcoinpaperwallet isn't. The BIP notes that "This methodology does not offer the ability to encrypt a known private key", which will be why bitcoinpaperwallet isn't using it.

**Comment by pointbiz** [comment]
@dooglus 
Please take a look at branch bip38walletdetails 
https://github.com/pointbiz/bitaddress.org/tree/bip38walletdetails
This commit https://github.com/pointbiz/bitaddress.org/commit/c2e7fcf85ec91f76107035bc109b910c5c38727d

**Comment by pointbiz** [comment]
v3.1.0 resolves this request.
